[module]

[module.hugoVersion]
min = "0.154.5"

[markup]
  [markup.highlight]
    guessSyntax = true
    lineNos = false
    noClasses = false


[params.elemental]
visibleAlternativeFormats = ["rss"]

[outputFormats.JSONResume]
baseName = "resume"
isPlainText = true
mediaType = "application/json"
permalinkable = true
rel = "alternate"
